application: bozhu-crypto
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*\.(css|js|txt))
  static_files: \1
  upload: (.*\.(css|js|txt))
  secure: always

- url: /paper
  static_dir: paper
  secure: always

- url: /slides
  static_dir: slides
  secure: always
